INC         := 
LIBS        := 
LIBS_DIR    := 

CPP_SRCS    := 
OBJS        := 
BIN         :=
SRC         := dane-smime
XPI         := dane-smime.xpi

all: build

build:
	(cd $(SRC);zip -r ../../../build/$(XPI) *)

test:

clean:
	rm -f *.o *.a *.so *~ *xpi


.PHONY: all build clean
